### PR TITLE
Add week0024 talk on deploying with git hooks

### PR DESCRIPTION
**Pull request by shanemgrey**

### CODE REVIEW

**Comment by mikeputnam** [comment]
:+1:

**Comment by zo0o0ot** [comment]
Nice.  I do have a site which is autodeploying using git hooks on Azure-
Github Repo: https://github.com/Leagueify/draftcharts-jetstrap

Site: http://draftcharts.azurewebsites.net/

Docs: https://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/

I'm not sure if you want this to become a platform specific discussion, but I thought that I'd throw this out there as a comment before editing the markdown.

**Comment by shanemgrey** [comment]
Platform specific examples would be great. 

Shane

**Comment by zo0o0ot** [comment]
https://github.com/appletonmakerspace/coder_cooperative_talks/pull/14

**Pull request merged**
